### ISSUE TITLE
长 JSON 默认展开很长，还需要下滑查找，加一个配置项可配置默认收起状态会比较方便

### ISSUE THREAD

**Issue by Andy1994** [rakuyoMo/JSONPreview#11]

**Comment by rakuyoMo** [comment]
This is possible, I will try to implement it this afternoon.

**Comment by rakuyoMo** [comment]
@Andy1994 

Now you can try the feature in the master branch.
The `JSONPreview.preview` method has a new `initialState` parameter, and passing in `.folded` will cause all slices to default to the folded state.

Next Monday (01/08/2024) I will officially release version 2.1.0, which will carry this feature.

**Comment by Andy1994** [comment]
感谢，已验证可用

**Comment by rakuyoMo** [comment]
[2.1.0](https://github.com/RakuyoKit/JSONPreview/releases/tag/2.1.0) has been officially released.
