### ISSUE TITLE
SwiftLint dependency

### ISSUE THREAD

**Issue by MarekSlaninka** [rakuyoMo/JSONPreview#25]
Hello, I have a problem after updating SPM packages in the project, and SwiftLint automaicaly updated to 0.55.1 

And I get this error: 
`product 'SwiftLintPlugin' required by package 'jsonpreview' target 'JSONPreview' not found in package 'SwiftLint'.`

Coul You please provide some resolution for this issue?
Thanks

**Comment by rakuyoMo** [comment]
Hello! 👋

SwiftLint 0.55.0 splits the `SwiftLintPlugin` plugin into `SwiftLintBuildToolPlugin` and `SwiftLintCommandPlugin`. For details, see: https://github.com/realm/SwiftLint/commit/e4e3545b712460509db6bc159838679f7b11b7cc

Currently, the latest version of JSONPreview (2.3.1) uses version 0.54.0 and has not been upgraded to the latest SwiftLint version.

So if you want to solve this problem, it is recommended to fix the SwiftLint version to 0.54.0 in the `Package.swift` file of your project.

**Comment by rakuyoMo** [comment]
RakuyoKit contains a general formatting plugin [RakuyoKit/swift](https://github.com/RakuyoKit/swift), and JSONPreview should migrate SwiftLint dependencies to this plugin. This plugin depends on and adapts to the latest SwiftLint version.

If you need SwiftLint version 0.55.0 or higher, please let me know and tell me the latest adaptation time (not as soon as possible), and I will consider updating JSONPreview.

**Comment by MarekSlaninka** [comment]
Hello, thanks for quick reply. I dont need exact version of SwiftLint, but i cannot update packages because it will update SwifLint too.  I will try to lock it using xcodeproj SPM manager.

**Comment by MarekSlaninka** [comment]
Hello, I just got error on newest Xcode for swiftlint, is there any ETA for updating it in your library? Thanks

**Comment by rakuyoMo** [comment]
> Hello, I just got error on newest Xcode for swiftlint, is there any ETA for updating it in your library? Thanks

Could you please try this PR #26? If it works fine, I will merge it and release a new version.

If you have any issues, please let me know which version of Swiftlint and Xcode you are using. I am currently still using 15.3 and have not upgraded to 16 beta.

**Comment by MarekSlaninka** [comment]
Hi, I am not able to select nor that branch, or commit in xcode. There is allways error. What am I doing wrong please?
![Snímka obrazovky 2024-08-08 o 10 29 46](https://github.com/user-attachments/assets/ec351466-616e-4930-9cd8-a6d3e741a353)
![Snímka obrazovky 2024-08-08 o 10 32 05](https://github.com/user-attachments/assets/c0f309f1-4d11-4ecb-b130-ea1b46dab3b5)

**Comment by MarekSlaninka** [comment]
Hello, I have a problem, when i select this branch, it will show this error
![Snímka obrazovky 2024-08-08 o 10 53 09](https://github.com/user-attachments/assets/3d5711b0-2bc2-4618-9ad2-6dd93e531010)

**Comment by rakuyoMo** [comment]
> Hello, I have a problem, when i select this branch, it will show this error ![Snímka obrazovky 2024-08-08 o 10 53 09](https://private-user-images.githubusercontent.com/5960482/356151680-3d5711b0-2bc2-4618-9ad2-6dd93e531010.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDc1OTEsIm5iZiI6MTcyMzEwNzI5MSwicGF0aCI6Ii81OTYwNDgyLzM1NjE1MTY4MC0zZDU3MTFiMC0yYmMyLTQ2MTgtOWFkMi02ZGQ5M2U1MzEwMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDg1NDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmMyMWRiMDIyZGYzNTFhMTgxNTc0YmYxNmUwODNiOTg0NTZkNjc1NjlkZTQ5MjVmZWNiMDQ3YjNkZmU2M2JhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zp93ZBjVuiNzX4pcJSJTH6Q7apPWyRALm25rymty4d0)

<img width="1605" alt="image" src="https://github.com/user-attachments/assets/a589208f-8c34-4ccd-a5be-ab9fd8c853ea">

I tried using the branch for reference in demo and it worked without any problems.

If you use `Package.swift` instead of Xcode to manage SPM dependencies, you can try using `.package(url: branch:)`.

```swift
.package(url: "https://github.com/RakuyoKit/JSONPreview.git", branch: "feature/swiftlint")
```

@MarekSlaninka Could you please describe your current environment and operation steps in more detail?

**Comment by MarekSlaninka** [comment]
Im sorry, i got it to work. Its okay, I could also update SwftLint to newest version. Thank You and sorry again

**Comment by rakuyoMo** [comment]
Now that version [2.3.2](https://github.com/RakuyoKit/JSONPreview/releases/tag/2.3.2) has been released
