### ISSUE TITLE
项目很不错，希望加入搜索功能

### ISSUE THREAD

**Issue by lovesunstar** [rakuyoMo/JSONPreview#6]
Examples of actions after searching as follows:
locate a specific location
highlight targets

**Comment by rakuyoMo** [comment]
> No description provided.

What kind of search functionality would you like me to provide? Can you be more specific in your description?

For example, to locate a specific location of a target after searching?

**Comment by rakuyoMo** [comment]
Close with #13 

Currently, automatic scrolling to the target position is not implemented, but the method returns the line number index, so the caller can manually scroll to the corresponding position.
