### ISSUE TITLE
UITableViewCell can't calculate a dynamic size for JSONPreview subview

### ISSUE THREAD

**Issue by decim92** [rakuyoMo/JSONPreview#8]
Is there a way to calculate the size of the JSONPreview so that we can have dynamic sizes inside UITableViewCells?

Also, is there a way to disable the line number column?

**Comment by rakuyoMo** [comment]
> Is there a way to calculate the size of the JSONPreview so that we can have dynamic sizes inside UITableViewCells?

Perhaps you could get the full height in the `preview(_: style: completion:)` callback via the `jsonTextView.contentSize` property. Then refresh your UITableView view to use the latest height value.

> Also, is there a way to disable the line number column?

Unfortunately, there is no way to do this at the moment. If you need it, I think I can add it subsequently and the feature should be easy to implement.

**Comment by rakuyoMo** [comment]
Version 2.1.0 will provide the function of hiding line numbers. I will close this issue after it is released

**Comment by rakuyoMo** [comment]
[2.1.0](https://github.com/RakuyoKit/JSONPreview/releases/tag/2.1.0) has been officially released, providing the function of hiding row numbers and providing a reference demo for use in UITableView.
