### ISSUE TITLE
JSONPreview decorator didSet func crash

### ISSUE THREAD

**Issue by mxh-mo** [rakuyoMo/JSONPreview#9]
JSONPreview decorator didSet func crash：
<img width="1027" alt="image" src="https://github.com/RakuyoKit/JSONPreview/assets/16602188/91212e98-78a4-403b-894e-f5cb2a722f9a">
<img width="2300" alt="image" src="https://github.com/RakuyoKit/JSONPreview/assets/16602188/2d57d43c-b5ca-41ce-8e39-9c4696fde581">

**Comment by rakuyoMo** [comment]
Can you provide me with the json you previewed so I can try to reproduce the issue.

**Comment by mxh-mo** [comment]
Not mandatory

**Comment by rakuyoMo** [comment]
close with [#10](https://github.com/RakuyoKit/JSONPreview/issues/10)
